import React from 'react';
import {withStyles} from "@material-ui/core";

const styles = theme => ({
    root: {
        display: 'flex',
        flexWrap: 'wrap',
    },
    pre: {
        'white-space': 'pre-wrap',
    },
});

function PrivacyPolicy(props) {
    const { classes } = props;
    return (
        <div>
            <h2>Copyright (C) 2020  Network New Technologies Inc.</h2>
            <pre className={classes.pre}>
                Taiji is a free and open-source Wallet for Android.
            </pre>
            <pre className={classes.pre}>
                This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License published by the Free Software Foundation, either version 3 or any later version.
            </pre>
            <pre className={classes.pre}>
                This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
            </pre>
            <pre className={classes.pre}>
                You should have received a copy of the GNU General Public License along with this program. If not, please visit <a href="https://www.gnu.org/licenses/gpl-3.0.html" rel="noreferrer noopener" target="_blank">GNU General Public License</a>
            </pre>
            <h2>Privacy Policy</h2>
            <pre className={classes.pre}>
                Although we have users' wallets persisted on our server, they are protected with users' passwords. It is recommended to create at least another wallet with Android Wallet on your phone. For the wallet with more currencies and tokens, please export from the phone and save it offline. Transaction information such as account balances and transaction histories is part of a publicly available and distributed ledger on the taiji blockchain hosted on our servers and cached by others. Your Wallets, including its private keys generated by this application, are stored only locally on our servers and are never shared or transmitted to the Internet.
            </pre>
            <pre className={classes.pre}>
                If there are further questions, please contact us as we are happy to help you in this regard.
            </pre>
            <pre className={classes.pre}>
                By using this application, you agree to our Privacy Policy. Please do not further access or use the application if you disagree.
            </pre>
        </div>
    )
}

export default withStyles(styles)(PrivacyPolicy);
